USE slhdsms;
CREATE TABLE IF NOT EXISTS HY_MMXP_F(
	STCD CHAR(8) NOT NULL COMMENT '测站码',
	YR DECIMAL(4) NOT NULL COMMENT '年',
	BGTM DATETIME COMMENT '起时间',
	MXPDR DECIMAL(4) NOT NULL COMMENT '最大降水量时段长 单位min',
	mxp DECIMAL(5,1) COMMENT '最大降水量 单位mm',
	mxprc CHAR(4) COMMENT '最大降水量注解码',
	PRIMARY KEY (STCD,MXPDR,YR)
	
);

CREATE TABLE IF NOT EXISTS HY_HMXP_F(
	STCD CHAR(8) NOT NULL COMMENT '测站码',
	YR DECIMAL(4) NOT NULL COMMENT '年',
	BGTM DATETIME COMMENT '起时间',
	MXPDR DECIMAL(4) NOT NULL COMMENT '最大降水量时段长 单位 h',
	mxp DECIMAL(5,1) COMMENT '最大降水量 单位mm',
	mxprc CHAR(4) COMMENT '最大降水量注解码',
	PRIMARY KEY (STCD,MXPDR,YR)
	
);

CREATE TABLE IF NOT EXISTS HY_DMXP_F(
	STCD CHAR(8) NOT NULL COMMENT '测站码',
	YR DECIMAL(4) NOT NULL COMMENT '年',
	BGDT DATE COMMENT '起始日期',
	MXPDR DECIMAL(4) NOT NULL COMMENT '最大降水量时段长',
	mxp DECIMAL(5,1) COMMENT '最大降水量 单位mm',
	mxprc CHAR(4) COMMENT '最大降水量注解码',
	PRIMARY KEY (STCD,MXPDR,YR)
	
);